Matrix factorization basic theory
SpecialeBajs/Rapport pull request #14
Opened 2020-10-19 11:03 UTC by jenspetur94

2020-10-19 11:28 UTC, MathiasLybech requested changes

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +Collaborative filtering on the other hand uses both similarity between users and items to provide recommendations.
Er det ikke similarity between users and users?

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +This means that collaborative filtering recommends and item to a user based on a similar user.
```suggestion
This means that collaborative filtering recommends an item to a user based on a similar user.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +But collaborative filtering suffers from the cold start problem which means that it does not deal well with new users that has not like anything yet.
```suggestion
But collaborative filtering suffers from the cold start problem which means that it does not deal well with new users that have no rated items.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +In general collaborative filtering is more accurate than content-based filtering.
Kilde?

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +The data concerning users and items can be represented as matrix where each row represents a user and each column an item.
```suggestion
The data concerning users and items can be represented as a matrix where each row represents a user and each column an item.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +The entries in the matrix will then be the explicit feedback given for that item by the user of there is any.
```suggestion
The entries in the matrix will then be the explicit feedback given for that item by the user if there is any.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +Matrix factorization can then be used to infer user preference for the items not rated by the user by using implicit feedback.
Beskriv kort hvad implicit feedback er

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +This is done by mapping users and items to a joint  latent factor space of dimensionality $f$.
```suggestion
This is done by mapping users and items to a joint latent factor space of dimensionality $f$.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +For each item i their corresponding entry in $q_i$ will meassure the extent in which the item posseses the feature and for each user u their corresponding entry in $q_u$ will meassure their liking to
```suggestion
For each item i their corresponding entry in $q_i$ will measure the extent in which the item possesses the feature and for each user u their corresponding entry in $q_u$ will measure their liking to each feature.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +The main challenge of using the matrix factorization model is finding a good algortihm for computing the mapping of each item to the factor vectors $q_i$ and $q_u$.
```suggestion
The main challenge of using the matrix factorization model is finding a good algorithm for computing the mapping of each item to the factor vectors $q_i$ and $q_u$.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +After the factor vectors are computed the task of estimating the rating a user will give an item is easy through the following equation $r_ui \: = \: q_i^T p_u$ where $r_ui$ is the resulting ratings
```suggestion
After the factor vectors are computed the task of estimating the rating a user will give an item is easy through the following equation $r_{ui} \: = \: q_i^T p_u$ where $r_{ui}$ is the resulting ratings matrix.
```

2020-10-19 11:28 UTC, MathiasLybech commented on article/basic-theory.tex
> +After the factor vectors are computed the task of estimating the rating a user will give an item is easy through the following equation $r_ui \: = \: q_i^T p_u$ where $r_ui$ is the resulting ratings
ved r_ui vil kun u være nede. ved r_{ui} vil både u og i være nede.

2020-10-20 07:30 UTC, Fatdet requested changes

2020-10-20 07:30 UTC, Fatdet commented on article/basic-theory.tex
> +Content-based filtering is done by recommending items that are similar to items that the user had like before.
```suggestion
Content-based filtering is done by recommending items that are similar to items that the user has liked before.
```

2020-10-20 07:30 UTC, Fatdet commented on article/basic-theory.tex
> +In general collaborative filtering is more accurate than content-based filtering \cite{Matrix-factorization-techniques}.
```suggestion
In general, collaborative filtering is more accurate than content-based filtering \cite{Matrix-factorization-techniques}.
```

2020-10-20 07:30 UTC, Fatdet commented on article/basic-theory.tex
> +For each item i their corresponding entry in $q_i$ will measure the extent in which the item possesses the feature and for each user u their corresponding entry in $q_u$ will measure their liking to
```suggestion
For each item i the corresponding entry in $q_i$ will measure the extent in which the item possesses the feature and for each user u the corresponding entry in $q_u$ will measure their liking to each feature.
```

2020-10-20 08:22 UTC, Fatdet approved these changes

2020-10-20 08:22 UTC, MathiasLybech approved these changes

2020-10-20 08:25 UTC, merged