[wip] method for PAS
SpecialeBajs/Rapport pull request #19
Opened 2020-11-12 10:34 UTC by MathiasLybech

2020-11-23 14:46 UTC, jenspetur94 requested changes

2020-11-23 14:46 UTC, jenspetur94 commented on article/method.tex
> +Let the user-item, item-price and item-category interactions matrix be $R \in \mathbb{R}^{I \times U + C + P}$, where $I$ denotes the number of users, $U, C, P$ denotes the number of users, categorie
```suggestion
Let the user-item, item-price and item-category interactions matrix be $R \in \mathbb{R}^{I \times U + C + P}$, where $I$ denotes the number of items, $U, C, P$ denotes the number of users, categories and prices.
```

2020-11-23 14:48 UTC, Fatdet approved these changes

2020-11-23 15:01 UTC, jenspetur94 requested changes

2020-11-24 08:57 UTC, jenspetur94 approved these changes

2020-11-24 09:09 UTC, merged