Intro og datasæt rettelser
SpecialeBajs/Rapport pull request #55
Opened 2020-12-10 08:08 UTC by Fatdet

2020-12-10 08:13 UTC, MathiasLybech requested changes

2020-12-10 08:13 UTC, MathiasLybech commented on article/equal-data.tex
> +It consist of 20091 items and 24384 users.
```suggestion
It consists of 20091 items and 24384 users.
```

2020-12-10 08:13 UTC, MathiasLybech commented on article/equal-data.tex
> +We utilized 10 core settings meaning we only use items and users which have had atleast 10 interactions.
```suggestion
We utilized 10 core settings meaning we only use items and users which have had at least 10 interactions.
```

2020-12-10 08:13 UTC, MathiasLybech commented on article/introduction.tex
> +Generally the most common way to achieve this is to firstly learn latent features to represent a user and an item, this process is also called embedding.
```suggestion
Generally, the most common way to achieve this is to firstly learn latent features to represent a user and an item, this process is also called embedding.
```

2020-12-10 08:13 UTC, MathiasLybech commented on article/introduction.tex
> +Secondly the embeddings are used for performing predictions.
```suggestion
Secondly, the embeddings are used for performing predictions.
```

2020-12-10 08:13 UTC, MathiasLybech commented on article/introduction.tex
> +An early model for CF is Matrix Factorization, which embeds user and item ID as vectors and and uses the dot product to predict whether a user would like a certain item.
```suggestion
An early model for CF is Matrix Factorization, which embeds user and item ID as vectors and uses the dot product to predict whether a user would like a certain item.
```

2020-12-10 14:26 UTC, MathiasLybech approved these changes

2020-12-14 08:55 UTC, jenspetur94 approved these changes

2020-12-14 09:48 UTC, merged