ngcf embedding and moving text around
SpecialeBajs/Rapport pull request #56
Opened 2020-12-10 11:31 UTC by MathiasLybech

2020-12-10 14:14 UTC, jenspetur94 requested changes

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +where $\alpha$ is set to $1/(K + 1)$.
```suggestion
where $\alpha$ is set to $1/(K + 1)$ and is used to normalize the embeddings.
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +The embeddings for NGCF are calculated as follows \cite{NGCF_2019},
```suggestion
The embeddings for NGCF are constructed as follows \cite{NGCF_2019},
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +where $E^{(l)} \in \mathbb{R}^{I+U \times T}$ are the item and user embedding after $l$ convolutions.
```suggestion
where $E^{(l)} \in \mathbb{R}^{I+U \times T}$ are the item and user embeddings after $l$ convolutions.
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +The difference between NGCF and LightGCN can be seen to be that NGCF utilizes the $LeakyReLU$ activation function as well as using the trainable weight matrices.
```suggestion
The difference between NGCF and LightGCN are that NGCF utilizes the $LeakyReLU$ activation function as well as using the trainable weight matrices.
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +Where NGCF and LightGCN are constructed for collaborative filtering without additional side information, the construction of the embeddings in Price-Aware recommendation focus' on creating additional
```suggestion
While NGCF and LightGCN are constructed for collaborative filtering without additional side information, the construction of the embeddings in Price-Aware recommendation focuses on constructing additional embeddings for both price and category, and utilizing these to compute predictions.
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/compare-embeddings.tex
> +Where NGCF and LightGCN are constructed for collaborative filtering without additional side information, the construction of the embeddings in Price-Aware recommendation focus' on creating additional
måske dele sætningen lidt op. Den er godt nok lang

2020-12-10 14:14 UTC, jenspetur94 commented on article/embedding-impl.tex
> +% This section should be considered being used in appendix alongside the code of the embedding
```suggestion
% This section should be considered to be used in appendix alongside the code of the embedding
```

2020-12-10 14:14 UTC, jenspetur94 commented on article/embedding-impl.tex
> +When creating the embeddings in price-aware recommendation the two required inputs are the feature matrices, which are the adjacency matrix, and an identity matrix with the size n $\times$ n where n
Er adjacency matricen og identity matricen feature matrices ?

2020-12-10 15:21 UTC, Fatdet requested changes

2020-12-10 15:21 UTC, Fatdet commented on article/compare-embeddings.tex
> +where $e_u$, $e_i$, $e_c$, and $e_p$ are the embeddings for user $u$, item $i$, category $c$ and price $p$ respectively.
husk at beskrive embeddings i ligning 3!

2020-12-10 15:21 UTC, Fatdet commented on article/compare-embeddings.tex
> +    e_u = \sum_{k=0}^{K} \alpha_k e_u^{(k)};\;\;\; e_i = \sum_{k=0}^{K} \alpha_k e_i^{(k)},
Nævn lige K

2020-12-11 09:36 UTC, MathiasLybech commented on article/compare-embeddings.tex
> +\subsubsection{Price-aware recommendation}\label{subsubsec:price}
Den beskrivelse har jeg tilføjet til introduktionen, da det er gældende for dem alle

2020-12-14 08:53 UTC, Fatdet approved these changes

2020-12-14 09:21 UTC, jenspetur94 approved these changes

2020-12-14 09:34 UTC, merged