Factorization machines in basic-theory
SpecialeBajs/Rapport pull request #59
Opened 2020-12-14 08:34 UTC by jenspetur94

2020-12-14 08:42 UTC, MathiasLybech requested changes

2020-12-14 08:42 UTC, MathiasLybech commented on appendix/basic-theory.tex
> +Factorization machines(FM) are a general-purpouse supervised learning algorithm.
```suggestion
Factorization machines(FM) are a general-purpose supervised learning algorithm.
```

2020-12-14 08:42 UTC, MathiasLybech commented on appendix/basic-theory.tex
> +The problem that FM's solve is that if the dataset is very sparse there might not be enough data to estimate interaction between variables.
Tror ikke at jeg helt forstår denne sætning

2020-12-14 08:42 UTC, MathiasLybech commented on appendix/basic-theory.tex
> +FM's are able to do this well because because they break the independence of the parameters by factorizing them.
```suggestion
FM's are able to do this well because they break the independence of the parameters by factorizing them.
```

2020-12-14 09:00 UTC, Fatdet requested changes

2020-12-14 13:04 UTC, Fatdet requested changes

2020-12-14 13:04 UTC, Fatdet commented on appendix/basic-theory.tex
> +Where the parameters that have to be estimated are:
hvis v_i er feature matrix og x_i er feature set

2020-12-15 13:58 UTC, Fatdet requested changes

2020-12-15 13:58 UTC, Fatdet commented on appendix/basic-theory.tex
> +Factorization machines(FM) are a general-purpose supervised learning algorithm and where originally introduced by Steffen Rendle \cite{factorization_machines}.
```suggestion
Factorization machines(FM) are a general-purpose supervised learning algorithm and were originally introduced by Steffen Rendle \cite{factorization_machines}.
```

2020-12-15 15:23 UTC, MathiasLybech approved these changes

2020-12-16 08:53 UTC, Fatdet approved these changes

2020-12-16 13:18 UTC, merged