Introducing NGCF PAS and LGCN PAS
SpecialeBajs/Rapport pull request #66
Opened 2020-12-16 12:08 UTC by MathiasLybech

2020-12-16 13:19 UTC, Fatdet approved these changes

2020-12-17 10:08 UTC, jenspetur94 approved these changes

2020-12-17 10:13 UTC, jenspetur94 requested changes

2020-12-17 10:13 UTC, jenspetur94 commented on article/conclusion.tex
> +We focused on LightGCN, Neural Graph Collaborative Filtering, and Price-aware Recommendation, where we described differences in the construction of the adjacency matrix and the differences in the con
```suggestion
We focused on LightGCN, Neural Graph Collaborative Filtering, and Price-aware Recommendation, where we described differences in the construction of the adjacency matrices and the differences in the construction of the embeddings.
```

2020-12-17 10:13 UTC, jenspetur94 commented on article/conclusion.tex
> +However, the extensions LightGCN- and NGCF-PAS showed that NGCF is better suited for handling semantic representations, where LightGCN currently does not handle additional side information well.
```suggestion
However, the extensions LightGCN- and NGCF-PAS showed that NGCF is better suited for handling aditional side information, where LightGCN currently does not handle additional side information well.
```

2020-12-17 10:13 UTC, jenspetur94 commented on article/experiment.tex
> +The experiment are conducted on an Yelp Dataset to evaluate our proposed changes in LightGCN and NGCF.
```suggestion
The experiments are conducted on a Yelp Dataset to evaluate our proposed changes in LightGCN and NGCF.
```

2020-12-17 10:15 UTC, jenspetur94 approved these changes

2020-12-17 10:29 UTC, merged