dolog changes
SpecialeBajs/Rapport pull request #71
Opened 2020-12-18 12:16 UTC by MathiasLybech

2020-12-18 12:36 UTC, jenspetur94 requested changes

2020-12-18 12:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +The batch size is set to 1024.
```suggestion
The batch size is set to 2048.
```

2020-12-18 12:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +For optimization Adam is used with an initial learning rate of $1e-2$
```suggestion
For optimization Adam is used with an initial learning rate of $1e-4$
```

2020-12-18 12:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +PUP never specifies in their paper, how many convolutions they used in their experiments, but with the code we received, we came to the conclusion that they only use 1 convolution in PUP.
måske skrive om hvad vi har brugt i PUP som parametre

2020-12-18 12:36 UTC, jenspetur94 commented on article/performance-comparisons.tex
> +It could be because LightGCN does not utilize feature transformation and the nonlinear activation function.
```suggestion
It could be because LightGCN does not utilize feature transformation and uses a nonlinear activation function.
```

2020-12-20 09:17 UTC, Fatdet approved these changes

2020-12-20 09:36 UTC, jenspetur94 requested changes

2020-12-20 09:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +All baseline methods uses BPR loss and have the embedding size set to 64.
```suggestion
All baseline methods use BPR loss as their loss function and have the embedding size set to 64.
```

2020-12-20 09:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +The number convolution is set to 1.
ud fra de som du skriver i den næste sætning passer det vel ikke. Vi sætter ikke convolutions til noget som helst 🤔 
```suggestion
```

2020-12-20 09:36 UTC, jenspetur94 commented on article/experimental-settings.tex
> +The evaluation metrics for rating top k recommendation, we utilize Recall@K and NDCG@K where K is set to 50 and 100.
```suggestion
The evaluation metrics used for rating top k recommendation are Recall@K and NDCG@K where K is set to 50 and 100.
```

2020-12-20 10:09 UTC, jenspetur94 approved these changes

2020-12-20 10:12 UTC, merged